import { Color } from "@/utils";

export const BUTTON_CONTAINED_COLOR: { [key in Color]: string } = {
    slate: "bg-slate-600 hover:bg-slate-600/90 text-white",
    gray: "bg-gray-600 hover:bg-gray-600/90 text-white",
    zinc: "bg-zinc-600 hover:bg-zinc-600/90 text-white",
    neutral: "bg-neutral-600 hover:bg-neutral-600/90 text-white",
    stone: "bg-stone-600 hover:bg-stone-600/90 text-white",
    red: "bg-red-600 hover:bg-red-600/90 text-white",
    orange: "bg-orange-600 hover:bg-orange-600/90 text-white",
    amber: "bg-amber-600 hover:bg-amber-600/90 text-white",
    yellow: "bg-yellow-600 hover:bg-yellow-600/90 text-white",
    lime: "bg-lime-600 hover:bg-lime-600/90 text-white",
    green: "bg-green-600 hover:bg-green-600/90 text-white",
    emerald: "bg-emerald-600 hover:bg-emerald-600/90 text-white",
    teal: "bg-teal-600 hover:bg-teal-600/90 text-white",
    cyan: "bg-cyan-600 hover:bg-cyan-600/90 text-white",
    sky: "bg-sky-600 hover:bg-sky-600/90 text-white",
    blue: "bg-blue-600 hover:bg-blue-600/90 text-white",
    indigo: "bg-indigo-600 hover:bg-indigo-600/90 text-white",
    violet: "bg-violet-600 hover:bg-violet-600/90 text-white",
    purple: "bg-purple-600 hover:bg-purple-600/90 text-white",
    fuchsia: "bg-fuchsia-600 hover:bg-fuchsia-600/90 text-white",
    pink: "bg-pink-600 hover:bg-pink-600/90 text-white",
    rose: "bg-rose-600 hover:bg-rose-600/90 text-white",
};

export const BUTTON_OUTLINED_COLOR: { [key in Color]: string } = {
    slate: "bg-transparent hover:bg-slate-600 text-slate-600 hover:text-white border border-slate-600",
    gray: "bg-transparent hover:bg-gray-600 text-gray-600 hover:text-white border border-gray-600",
    zinc: "bg-transparent hover:bg-zinc-600 text-zinc-600 hover:text-white border border-zinc-600",
    neutral:
        "bg-transparent hover:bg-neutral-600 text-neutral-600 hover:text-white border border-neutral-600",
    stone: "bg-transparent hover:bg-stone-600 text-stone-600 hover:text-white border border-stone-600",
    red: "bg-transparent hover:bg-red-600 text-red-600 hover:text-white border border-red-600",
    orange: "bg-transparent hover:bg-orange-600 text-orange-600 hover:text-white border border-orange-600",
    amber: "bg-transparent hover:bg-amber-600 text-amber-600 hover:text-white border border-amber-600",
    yellow: "bg-transparent hover:bg-yellow-600 text-yellow-600 hover:text-white border border-yellow-600",
    lime: "bg-transparent hover:bg-lime-600 text-lime-600 hover:text-white border border-lime-600",
    green: "bg-transparent hover:bg-green-600 text-green-600 hover:text-white border border-green-600",
    emerald:
        "bg-transparent hover:bg-emerald-600 text-emerald-600 hover:text-white border border-emerald-600",
    teal: "bg-transparent hover:bg-teal-600 text-teal-600 hover:text-white border border-teal-600",
    cyan: "bg-transparent hover:bg-cyan-600 text-cyan-600 hover:text-white border border-cyan-600",
    sky: "bg-transparent hover:bg-sky-600 text-sky-600 hover:text-white border border-sky-600",
    blue: "bg-transparent hover:bg-blue-600 text-blue-600 hover:text-white border border-blue-600",
    indigo: "bg-transparent hover:bg-indigo-600 text-indigo-600 hover:text-white border border-indigo-600",
    violet: "bg-transparent hover:bg-violet-600 text-violet-600 hover:text-white border border-violet-600",
    purple: "bg-transparent hover:bg-purple-600 text-purple-600 hover:text-white border border-purple-600",
    fuchsia:
        "bg-transparent hover:bg-fuchsia-600 text-fuchsia-600 hover:text-white border border-fuchsia-600",
    pink: "bg-transparent hover:bg-pink-600 text-pink-600 hover:text-white border border-pink-600",
    rose: "bg-transparent hover:bg-rose-600 text-rose-600 hover:text-white border border-rose-600",
};

export const BUTTON_LIGHT_COLOR: { [key in Color]: string } = {
    slate: "bg-transparent hover:bg-slate-600/20 text-slate-600",
    gray: "bg-transparent hover:bg-gray-600/20 text-gray-600",
    zinc: "bg-transparent hover:bg-zinc-600/20 text-zinc-600",
    neutral: "bg-transparent hover:bg-neutral-600/20 text-neutral-600",
    stone: "bg-transparent hover:bg-stone-600/20 text-stone-600",
    red: "bg-transparent hover:bg-red-600/20 text-red-600",
    orange: "bg-transparent hover:bg-orange-600/20 text-orange-600",
    amber: "bg-transparent hover:bg-amber-600/20 text-amber-600",
    yellow: "bg-transparent hover:bg-yellow-600/20 text-yellow-600",
    lime: "bg-transparent hover:bg-lime-600/20 text-lime-600",
    green: "bg-transparent hover:bg-green-600/20 text-green-600",
    emerald: "bg-transparent hover:bg-emerald-600/20 text-emerald-600",
    teal: "bg-transparent hover:bg-teal-600/20 text-teal-600",
    cyan: "bg-transparent hover:bg-cyan-600/20 text-cyan-600",
    sky: "bg-transparent hover:bg-sky-600/20 text-sky-600",
    blue: "bg-transparent hover:bg-blue-600/20 text-blue-600",
    indigo: "bg-transparent hover:bg-indigo-600/20 text-indigo-600",
    violet: "bg-transparent hover:bg-violet-600/20 text-violet-600",
    purple: "bg-transparent hover:bg-purple-600/20 text-purple-600",
    fuchsia: "bg-transparent hover:bg-fuchsia-600/20 text-fuchsia-600",
    pink: "bg-transparent hover:bg-pink-600/20 text-pink-600",
    rose: "bg-transparent hover:bg-rose-600/20 text-rose-600",
};

export const BUTTON_CONTAINED_ICON_COLOR: { [key in Color]: string } = {
    slate: "text-white",
    gray: "text-white",
    zinc: "text-white",
    neutral: "text-white",
    stone: "text-white",
    red: "text-white",
    orange: "text-white",
    amber: "text-white",
    yellow: "text-white",
    lime: "text-white",
    green: "text-white",
    emerald: "text-white",
    teal: "text-white",
    cyan: "text-white",
    sky: "text-white",
    blue: "text-white",
    indigo: "text-white",
    violet: "text-white",
    purple: "text-white",
    fuchsia: "text-white",
    pink: "text-white",
    rose: "text-white",
};

export const BUTTON_OUTLINED_ICON_COLOR: { [key in Color]: string } = {
    slate: "text-slate-600 group-hover:text-white",
    gray: "text-gray-600 group-hover:text-white",
    zinc: "text-zinc-600 group-hover:text-white",
    neutral: "text-neutral-600 group-hover:text-white",
    stone: "text-stone-600 group-hover:text-white",
    red: "text-red-600 group-hover:text-white",
    orange: "text-orange-600 group-hover:text-white",
    amber: "text-amber-600 group-hover:text-white",
    yellow: "text-yellow-600 group-hover:text-white",
    lime: "text-lime-600 group-hover:text-white",
    green: "text-green-600 group-hover:text-white",
    emerald: "text-emerald-600 group-hover:text-white",
    teal: "text-teal-600 group-hover:text-white",
    cyan: "text-cyan-600 group-hover:text-white",
    sky: "text-sky-600 group-hover:text-white",
    blue: "text-blue-600 group-hover:text-white",
    indigo: "text-indigo-600 group-hover:text-white",
    violet: "text-violet-600 group-hover:text-white",
    purple: "text-purple-600 group-hover:text-white",
    fuchsia: "text-fuchsia-600 group-hover:text-white",
    pink: "text-pink-600 group-hover:text-white",
    rose: "text-rose-600 group-hover:text-white",
};

export const BUTTON_LIGHT_ICON_COLOR: { [key in Color]: string } = {
    slate: "text-slate-600",
    gray: "text-gray-600",
    zinc: "text-zinc-600",
    neutral: "text-neutral-600",
    stone: "text-stone-600",
    red: "text-red-600",
    orange: "text-orange-600",
    amber: "text-amber-600",
    yellow: "text-yellow-600",
    lime: "text-lime-600",
    green: "text-green-600",
    emerald: "text-emerald-600",
    teal: "text-teal-600",
    cyan: "text-cyan-600",
    sky: "text-sky-600",
    blue: "text-blue-600",
    indigo: "text-indigo-600",
    violet: "text-violet-600",
    purple: "text-purple-600",
    fuchsia: "text-fuchsia-600",
    pink: "text-pink-600",
    rose: "text-rose-600",
};
